batch_size: 8
iters: 80000

train_dataset:
  type: TuSimple
  data_root: /home/aistudio/data
  split: trainval
  cut_height: 160
  ori_w_h: [720,1280]
  num_classes: 7
  test_json_file: /home/aistudio/data/test_label.json
  transforms:
    - type: RandomRotation
    - type: RandomHorizontalFlip
    - type: Resize
      target_size: [640,368]
    - type: Normalize

val_dataset:
  type: TuSimple
  data_root: /home/aistudio/data
  split: test
  cut_height: 160
  ori_w_h: [720,1280]
  num_classes: 7
  test_json_file: /home/aistudio/data/test_label.json
  transforms:
    - type: Resize
      target_size: [640,368]
    - type: Normalize

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 1.0e-4

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.0025
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
      weight: [0.4,1.,1.,1.,1.,1.,1.]
  coef: [1]
