_base_: '../_base_/culane.yml'

batch_size: 32
iters: 80000

model:
  type: SCNN
  backbone:
    type: ResNet50_vds
    output_stride: 8
    multi_grid: [1, 1, 1]
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  backbone_indices: [0,1,2]
  num_classes: 5
  featuremap_out_channel: 128
  thr: 0.3
  cut_height: 240 
  ori_img_h: 590
  img_height: 288
  ori_img_w: 1640
  img_width: 800
  out_conv: True
  use_exist: True

loss:
  types:
    - type: CrossEntropyLoss
      weight: [0.4,1.,1.,1.,1.]
    - type: BCELoss
  coef: [1,0.1]
