_base_: '../_base_/tusimple.yml'

batch_size: 32
iters: 80000

model:
  type: SCNN
  backbone:
    type: ResNet50_vds
    output_stride: 8
    multi_grid: [1, 1, 1]
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  backbone_indices: [0,1,2]
  num_classes: 7
  featuremap_out_channel: 128
  thr: 0.6
  cut_height: 160
  ori_img_h: 720
  img_height: 368
  ori_img_w: 1280
  img_width: 640
  out_conv: True
  use_exist: True

loss:
  types:
    - type: CrossEntropyLoss
      weight: [0.4,1.,1.,1.,1.,1.,1.]
    - type: BCELoss
  coef: [1,1]

# model:
#   type: DeepLabV3P
#   backbone:
#     type: ResNet50_vd
#     output_stride: 8
#     multi_grid: [1, 2, 4]
#     pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
#   num_classes: 7
#   backbone_indices: [0, 3]
#   aspp_ratios: [1, 12, 24, 36]
#   aspp_out_channels: 256
#   align_corners: False
#   pretrained: null

